default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Expense-App
  username : rubyuser
  password : rubyuser

test:
  <<: *default
  database: Expense-App_test

production:
  <<: *default
  database: Expense-App_production
  username: Expense-App
  password: <%= ENV['EXPENSE-APP_DATABASE_PASSWORD'] %>
